version: "3.5"

services:

  mysql:
    container_name: mysql-db
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bicicletas
      - MYSQL_USER=bicicletas
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
